global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"] # Agrega la configuración de Alertmanager

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  # Agrega una configuración para la monitorización de contenedores Docker
  - job_name: "docker"
    static_configs:
      - targets: ["loki:3100"]
        labels:
          job: "docker-logs"
