# Usa la imagen base de Node.js para construir la aplicación
FROM node:18-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código fuente
COPY . .

# Exponer el puerto en el que nginx sirve la aplicación
EXPOSE 3000

# Comando para iniciar nginx
CMD ["npm", "start"]